### ISSUE TITLE
Unable to change release channel

### ISSUE THREAD

**Issue by bill-orange** [FormerLurker/ArcWelderPlugin#119]
Oddly, I can no longer use the release channel selection.  Uninstalling ArcWelder had no effect.  

Perhaps you are in the process of releasing a change?
![arc_error](https://user-images.githubusercontent.com/18121312/104339805-dcc5f100-54ac-11eb-9c3e-bf517e78287c.png)

**Comment by FormerLurker** [comment]
It's a bug unfortunately.  I implemented the new per plugin release channels blind, before it was available, and sort of forgot I did that.  Then I made the mistake of deploying without testing it on the OctoPrint release candidate.  I'm going to talk to Gina to see if it can be fixed via an OctoPrint update.  Otherwise this will require a manual uninstall/reinstall as soon as the next version of ArcWelder is released (which will hopfully be soon, still working on testing the new build and dealing with some performance issues)

**Comment by bill-orange** [comment]
thanks, Makes sense.
