### ISSUE TITLE
Not working with Klipper - Extrusion issues

### ISSUE THREAD

**Issue by water-rhatt** [FormerLurker/ArcWelderPlugin#60]
FWIW, it does not appear to be working with Klipper. It seems to be trying to extrude all the filament for an arc at once, triggering the error:

`Move exceeds maximum extrusion (x.xxxmm^2 vs x.xxxxmm^2)`

Disabling the error doesn't solve the problem, you just end up with odd blobs at the end of an arc and stretches where there is no extrusion.

**Comment by FormerLurker** [comment]
That's interesting.  I've gotten lots of reports that it does work for klipper.  Are you sure arc support is enabled?  Maybe try sending a naked ```G2``` command and see what response you get.  If G2/G3 is disabled, and you are using absolute extrusion, you definitely could see the maximum extrusion error you are reporting.

If you find arcs are enabled (see the plugin page for a quick test of arc moves in the *Other Firmware* section [here](https://plugins.octoprint.org/plugins/arc_welder/)), could you attach your before/after gcode and the klipper firmware version (arc support was added in late 2019).

**Comment by stormbringer91** [comment]
I'd say it's pretty likely he's using absolute extrusion. Most slicers will default to absolute extrusion. The argument to use absolute vs relative extrusion is besides the point. 

Here's your fix, @water-rhatt 

Under "Extruder" in klipper config, add this line

`max_extrude_only_distance: 400.0`

For my personal setup, I needed to use the value of 400 because of my filament runout change script making a large extrusion movement in accordance with a homing move. 

I'm not exactly sure what the purpose of this restriction is in place for. But regardless, this is your fix.

**Comment by FormerLurker** [comment]
@stormbringer91, not saying you are wrong, I am not a klipper expert, but using absolute extrusion 100% could trigger this IF arc commands are disabled or unavailable.  Say 10 large G3 commands in a row are skipped because they are not understood.  Then the next command will extrude everything from the missed commands all at once.

**Comment by stormbringer91** [comment]
@FormerLurker I was agreeing with you, as far as the trigger being from absolute extrusion. The reason I state that this is the fix, is perhaps because of the way that klipper performs its advanced look ahead algorithms and how it compresses each event for the microcontroller. This could result in an abundance of lines that it reads in advanced and thinks it is extruding more than it actually is, since the code is so drastically compressed as it is into arcs. Only based on my personal experience. Maybe you're right and he missed that you actually need to enable arc support in the Klipper config. But I do use absolute extrusion and don't have any issues. 

ALSO! This is very important and I think you should perhaps let users of klipper know in your documentation. The arc resolution needs to be commented in as well, in the config file. 

`resolution: 0.05`

Now, I didn't do much homework on what value this actually needs to be. I assume it should be set to the minimum deviation that your arcwelder is set to? So that's what I did, to the default arcwelder value of 0.05mm. Otherwise, the klipper default resolution is 1.0mm, which then makes for circular features becoming almost octagonal depending on their size. I tested this using the mask holders for Covid19. The small circular strap features were what became octogonal, after applying the change of the above, it fixed it.

By the way, fantastic job with this plugin! Even with klipper and my skr mini 1.2 32bit board on my highly converted/modified ender 3 pro, I could not print the mask holders without stuttering in the gcode over USB when printing at 120mm/s 1000 acceleration, causing the printer to just stall while it would catch up, leading to big blobs on the surface from the stalled printer. Arcwelder solved the issue entirely. It's been working phenemonally for me for everything I've printed so far. I have even printed part of a very fine featured model with arcwelder and I can't see any errors in the print.

**Comment by FormerLurker** [comment]
@stormbringer91, regarding absolute extrusion, it is absolutely fine to use.

Regarding klipper docs, I am working on a 'check firmware' button as we speak.  If you know of any way to query klipper for the segment length value, that would be great!  I knew it had one, but not what the default was.  1mm is too low.  Marlin has a nifty min segments per circle setting, and I'm working to add a setting to enforce a min segment length.

You are correct that the 'resolution' in arc welder controls the minimim dimensional accuracy of your print in total after being welded.  Each arc is only allowed to deviate by +-1/2 of the resolution (+-0.025mm by default). The actual resolution of each arc printed is determined by the firmware (1mm per arc segment apparently by default in klipper).  I think 0.1mm per arc segment should produce great results if your hardway can handle it (klipper likely can).

**Comment by FormerLurker** [comment]
Oh, and i am glad you are having success with arc welder.  The problems you were having in the scenario you described is precisely what arc welder was designed to solve.

**Comment by water-rhatt** [comment]
> @stormbringer91, not saying you are wrong, I am not a klipper expert, but using absolute extrusion 100% could trigger this IF arc commands are disabled or unavailable. Say 10 large G3 commands in a row are skipped because they are not understood. Then the next command will extrude everything from the missed commands all at once.

I think this is going to prove to be it. I DID have gcode_arc enabled, but I must have had an old version of the firmware.  I updated klipper and was able to successfully print and aw file that had failed earlier. You are probably right that it was trying to ignore the g2/g3 and then extrude all at once.

I'll keep doing prints to see if the problem resurfaces, but for now updating Klipper was the answer.

**Comment by FormerLurker** [comment]
Excellent 👍 I will add the minimum klipper version to the firmware check button I am working on to hopefully prevent this in the future.

**Comment by stormbringer91** [comment]
@FormerLurker It doesn't seem that you can query for minimum segment at this time. [Here you can see the default arc segment](https://github.com/KevinOConnor/klipper/blob/master/config/example-extras.cfg#L508) figure this is something that could easily be implemented by the klipper Dev, as the extended gcode commands seem to provide easy implementation of such things. 

[Here's](https://www.klipper3d.org/G-Codes.html) a link to the supported extended gcode commands as is

**Comment by FormerLurker** [comment]
Cool, thanks!  I've been working on the firmware checker/configuration button today.
